name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Git repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set your Node.js version here

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Build and Export Next.js app
      - name: Build and Export Next.js app
        run: |
          yarn build

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          name: development
          AWS_S3_BUCKET: 'taidv-cloudfront-test' # Set your S3 bucket name as a secret
          AWS_ACCESS_KEY_ID: 'AKIA4IBRRSVZKDOUE7QD'
          AWS_SECRET_ACCESS_KEY: '0+nas/J+CG+SQq2ivYO9F4fRvpCHdM+P64NJyW7t'
          SOURCE_DIR: 'out'  # The output directory of next export